/**
 * Server functions — RPC endpoints generated by TanStack Start.
 *
 * These can safely be imported by client code: createServerFn returns a
 * callable whose handler body is stripped from the client bundle, leaving
 * only an RPC stub that fetches the server. Because client code imports
 * this module, it cannot live in `src/server/` (TanStack Start's
 * import-protection plugin denies client imports of any `**\/server/**`
 * path). The genuinely server-only state module stays in `src/server/`.
 */

import { createServerFn } from "@tanstack/react-start";
import {
  ackThreat,
  getDevices,
  getFleetSummary,
  getHealth,
  getIntel,
  getPrivacy,
  getThreats,
} from "@/server/state";

export const fetchFleetSummary = createServerFn({ method: "GET" }).handler(
  async () => getFleetSummary(),
);

export const fetchDevices = createServerFn({ method: "GET" }).handler(
  async () => getDevices(),
);

export const fetchThreats = createServerFn({ method: "GET" }).handler(
  async () => getThreats(),
);

export const fetchIntel = createServerFn({ method: "GET" }).handler(
  async () => getIntel(),
);

export const fetchHealth = createServerFn({ method: "GET" }).handler(
  async () => getHealth(),
);

export const fetchPrivacy = createServerFn({ method: "GET" }).handler(
  async () => getPrivacy(),
);

export const quarantineThreat = createServerFn({ method: "POST" })
  .inputValidator((id: unknown) => {
    if (typeof id !== "string" || id.length === 0) {
      throw new Error("threat id required");
    }
    return id;
  })
  .handler(async ({ data }) => ackThreat(data));
