/**
 * Server functions — RPC endpoints generated by TanStack Start.
 *
 * fetchDevices merges in-memory simulated devices with real agent
 * devices persisted in Upstash Redis (Vercel KV), so enrolled
 * gadgets survive across serverless function cold starts.
 */

import { createServerFn } from "@tanstack/react-start";
import {
  ackThreat,
  getDevices,
  getFleetSummary,
  getHealth,
  getIntel,
  getPrivacy,
  getThreats,
  type Device,
} from "@/server/state";
import { kvAvailable, kvLoadAgentDevices } from "@/server/kv";

/** Merge KV agent devices on top of the in-memory simulated ones. */
async function getMergedDevices(): Promise<Device[]> {
  const simulated = getDevices(); // in-memory, always available
  const agentDevices = await kvLoadAgentDevices(); // from Redis, may be []

  if (!agentDevices.length) return simulated;

  // Agent devices take priority; simulated fill the rest
  const merged = new Map(simulated.map((d) => [d.id, d]));
  for (const d of agentDevices) merged.set(d.id, d);

  return Array.from(merged.values()).sort((a, b) => b.risk - a.risk);
}

export const fetchFleetSummary = createServerFn({ method: "GET" }).handler(
  async () => getFleetSummary(),
);

export const fetchDevices = createServerFn({ method: "GET" }).handler(
  async () => getMergedDevices(),
);

export const fetchThreats = createServerFn({ method: "GET" }).handler(
  async () => getThreats(),
);

export const fetchIntel = createServerFn({ method: "GET" }).handler(
  async () => getIntel(),
);

export const fetchHealth = createServerFn({ method: "GET" }).handler(
  async () => getHealth(),
);

export const fetchPrivacy = createServerFn({ method: "GET" }).handler(
  async () => getPrivacy(),
);

export const quarantineThreat = createServerFn({ method: "POST" })
  .inputValidator((id: unknown) => {
    if (typeof id !== "string" || id.length === 0) {
      throw new Error("threat id required");
    }
    return id;
  })
  .handler(async ({ data }) => ackThreat(data));

/** Exposes whether KV is configured so the UI can show the right hint. */
export const fetchKvStatus = createServerFn({ method: "GET" }).handler(
  async () => ({ available: kvAvailable() }),
);
