/**
 * Server functions — these are RPC endpoints generated by TanStack Start.
 * The handler body runs only on the server; callers (loaders, hooks)
 * import these and call them like normal async functions.
 */

import { createServerFn } from "@tanstack/react-start";
import {
  ackThreat,
  getDevices,
  getFleetSummary,
  getHealth,
  getIntel,
  getPrivacy,
  getThreats,
} from "./state";

export const fetchFleetSummary = createServerFn({ method: "GET" }).handler(
  async () => getFleetSummary(),
);

export const fetchDevices = createServerFn({ method: "GET" }).handler(
  async () => getDevices(),
);

export const fetchThreats = createServerFn({ method: "GET" }).handler(
  async () => getThreats(),
);

export const fetchIntel = createServerFn({ method: "GET" }).handler(
  async () => getIntel(),
);

export const fetchHealth = createServerFn({ method: "GET" }).handler(
  async () => getHealth(),
);

export const fetchPrivacy = createServerFn({ method: "GET" }).handler(
  async () => getPrivacy(),
);

export const quarantineThreat = createServerFn({ method: "POST" })
  .inputValidator((id: unknown) => {
    if (typeof id !== "string" || id.length === 0) {
      throw new Error("threat id required");
    }
    return id;
  })
  .handler(async ({ data }) => ackThreat(data));
