/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is generated by TanStack Router. It is updated on every dev/build
// run, so manual edits will be overwritten. If you have just added a route
// file under src/routes/, running `bun dev` once will rewrite this.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as AIAssistantRouteImport } from './routes/ai-assistant'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)

const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)

const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)

const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)

const AIAssistantRoute = AIAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)

const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/threats': typeof ThreatsRoute
  '/logs': typeof LogsRoute
  '/network': typeof NetworkRoute
  '/ai-assistant': typeof AIAssistantRoute
  '/policies': typeof PoliciesRoute
  '/api/ingest': typeof ApiIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/threats': typeof ThreatsRoute
  '/logs': typeof LogsRoute
  '/network': typeof NetworkRoute
  '/ai-assistant': typeof AIAssistantRoute
  '/policies': typeof PoliciesRoute
  '/api/ingest': typeof ApiIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/threats': typeof ThreatsRoute
  '/logs': typeof LogsRoute
  '/network': typeof NetworkRoute
  '/ai-assistant': typeof AIAssistantRoute
  '/policies': typeof PoliciesRoute
  '/api/ingest': typeof ApiIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/threats'
    | '/logs'
    | '/network'
    | '/ai-assistant'
    | '/policies'
    | '/api/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices'
    | '/threats'
    | '/logs'
    | '/network'
    | '/ai-assistant'
    | '/policies'
    | '/api/ingest'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/threats'
    | '/logs'
    | '/network'
    | '/ai-assistant'
    | '/policies'
    | '/api/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRoute
  ThreatsRoute: typeof ThreatsRoute
  LogsRoute: typeof LogsRoute
  NetworkRoute: typeof NetworkRoute
  AIAssistantRoute: typeof AIAssistantRoute
  PoliciesRoute: typeof PoliciesRoute
  ApiIngestRoute: typeof ApiIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AIAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRoute,
  ThreatsRoute: ThreatsRoute,
  LogsRoute: LogsRoute,
  NetworkRoute: NetworkRoute,
  AIAssistantRoute: AIAssistantRoute,
  PoliciesRoute: PoliciesRoute,
  ApiIngestRoute: ApiIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
